"""
agent-network-monitor skill — OP-Sec Division, Tier 1 LLM (7B local).
Monitors network activity generated by J_Claw agents in the past 24h.
Scans logs for external connections, flags unknown domains, escalates if needed.
"""

import json
import logging
import re
from datetime import date, datetime, timezone, timedelta
from pathlib import Path

from runtime.config import MODEL_7B, OLLAMA_HOST, BASE_DIR
from runtime.ollama_client import chat_json, is_available

log = logging.getLogger(__name__)
MODEL    = MODEL_7B
LOGS_DIR = BASE_DIR / "logs"
OUT_DIR  = BASE_DIR / "divisions" / "op-sec" / "agent-network"

SAFE_DOMAINS = {
    "api.anthropic.com",
    "api.groq.com",
    "api.deepseek.com",
    "api.adzuna.com",
    "finance.yahoo.com",
    "query1.finance.yahoo.com",
    "localhost",
    "127.0.0.1",
}

# Regex to extract URLs / hostnames from log lines
URL_RE    = re.compile(r'https?://([a-zA-Z0-9.\-]+)(?:[:/]|$)', re.IGNORECASE)
# Also catch bare host references like "host=api.groq.com"
HOST_RE   = re.compile(r'(?:host|url|endpoint|base_url)\s*[=:]\s*["\']?https?://([a-zA-Z0-9.\-]+)', re.IGNORECASE)
LOOKBACK  = timedelta(hours=24)


# ── Helpers ────────────────────────────────────────────────────────────────────

def _is_recent_line(line: str, cutoff: datetime) -> bool:
    """Try to parse a timestamp from the start of a log line."""
    # Common formats: "2026-03-29 14:05:01" or "2026-03-29T14:05:01"
    m = re.match(r'(\d{4}-\d{2}-\d{2}[T ]\d{2}:\d{2}:\d{2})', line)
    if m:
        try:
            ts = datetime.fromisoformat(m.group(1).replace(" ", "T"))
            # Assume local naive → treat as UTC for comparison
            if ts.tzinfo is None:
                ts = ts.replace(tzinfo=timezone.utc)
            return ts > cutoff
        except Exception:
            pass
    return True  # Include if unparseable — erring on the side of inclusion


def _extract_domains_from_lines(lines: list[str], cutoff: datetime) -> list[str]:
    """Extract unique domain names from recent log lines."""
    domains: set[str] = set()
    for line in lines:
        if not _is_recent_line(line, cutoff):
            continue
        for pattern in (URL_RE, HOST_RE):
            for match in pattern.finditer(line):
                domain = match.group(1).lower().strip(".")
                # Strip port if present
                domain = domain.split(":")[0]
                if domain:
                    domains.add(domain)
    return sorted(domains)


def _read_logs(cutoff: datetime) -> tuple[list[str], int]:
    """
    Read all *.log files in LOGS_DIR.
    Returns (all_recent_lines, files_read).
    """
    if not LOGS_DIR.exists():
        return [], 0

    log_files = list(LOGS_DIR.glob("*.log"))
    if not log_files:
        return [], 0

    all_lines: list[str] = []
    for lf in log_files:
        try:
            text  = lf.read_text(encoding="utf-8", errors="replace")
            lines = text.splitlines()
            # Read last 5000 lines max per file to keep this fast
            recent = lines[-5000:] if len(lines) > 5000 else lines
            all_lines.extend(recent)
        except Exception as e:
            log.warning("agent-network-monitor: could not read %s — %s", lf.name, e)

    return all_lines, len(log_files)


def _categorize_domains(domains: list[str]) -> tuple[list[str], list[str], list[str]]:
    """
    Split domains into known (safe), unknown, and API-key-associated.
    Returns (known_domains, unknown_domains, api_key_domains).
    """
    known: list[str]      = []
    unknown: list[str]    = []
    api_key: list[str]    = []

    api_key_indicators = {"api.", ".api."}

    for d in domains:
        if d in SAFE_DOMAINS:
            known.append(d)
            if any(ind in d for ind in api_key_indicators):
                api_key.append(d)
        else:
            unknown.append(d)
            if any(ind in d for ind in api_key_indicators):
                api_key.append(d)

    # Also mark known API domains
    for d in known:
        if d not in api_key and d.startswith("api."):
            api_key.append(d)

    return sorted(set(known)), sorted(set(unknown)), sorted(set(api_key))


def _llm_summarize(
    domains: list[str],
    known: list[str],
    unknown: list[str],
    api_key_domains: list[str],
    call_count: int,
    files_read: int,
) -> str:
    """Use LLM to produce a network profile summary if available."""
    if not is_available(MODEL, host=OLLAMA_HOST):
        if unknown:
            return (
                f"Agent network scan (24h): {call_count} external calls detected across "
                f"{len(known)} known domain(s). {len(unknown)} UNKNOWN domain(s) flagged: "
                f"{', '.join(unknown[:5])}. Manual review recommended."
            )
        return (
            f"Agent network scan (24h): {call_count} external call(s) detected. "
            f"All {len(known)} domain(s) recognized as safe. No anomalies."
        )

    context = (
        f"Agent network scan — past 24 hours:\n"
        f"Log files scanned: {files_read}\n"
        f"External call references found: {call_count}\n"
        f"Known (safe) domains: {', '.join(known) or 'none'}\n"
        f"Unknown domains: {', '.join(unknown) or 'none'}\n"
        f"API-key-associated domains: {', '.join(api_key_domains) or 'none'}\n"
        f"Safe domain list: {', '.join(sorted(SAFE_DOMAINS))}"
    )

    messages = [
        {
            "role": "system",
            "content": (
                "You are the OP-Sec agent network monitor for J_Claw. "
                "Given the past 24h of agent network activity from log files, "
                "write a 2-sentence security posture statement. "
                "If unknown domains are present, flag them clearly. "
                "If all domains are on the safe list, confirm clean status. "
                "Be direct, no preamble."
            ),
        },
        {"role": "user", "content": context},
    ]

    try:
        result = chat_json(MODEL, messages, host=OLLAMA_HOST, temperature=0.1, max_tokens=200)
        if isinstance(result, dict):
            return result.get("summary", str(result))
        return str(result).strip()
    except Exception as e:
        log.warning("agent-network-monitor LLM failed: %s", e)
        if unknown:
            return f"Network scan: {len(unknown)} unknown domain(s) detected — review required."
        return f"Network scan: {len(known)} known domain(s) seen, no anomalies."


# ── Main entry point ───────────────────────────────────────────────────────────

def run(**kwargs) -> dict:
    """
    Monitors agent-generated network activity for the past 24h.
    Flags unknown external domains and escalates if found.
    Saves report to divisions/op-sec/agent-network/YYYYMMDD_HHMMSS_network.json.
    XP: 8.
    """
    now       = datetime.now(timezone.utc)
    cutoff    = now - LOOKBACK
    timestamp = now.strftime("%Y%m%d_%H%M%S")

    # ── Read logs ──────────────────────────────────────────────────────────────
    lines, files_read = _read_logs(cutoff)

    if not lines:
        status  = "partial"
        summary = (
            "No log data available for agent network scan. "
            "Logs directory empty or missing."
        )
        report = {
            "timestamp":         now.isoformat(),
            "date":              date.today().isoformat(),
            "status":            status,
            "summary":           summary,
            "external_calls_24h": 0,
            "known_domains":     [],
            "unknown_domains":   [],
            "api_key_domains":   [],
            "files_scanned":     files_read,
            "escalate":          False,
        }
        OUT_DIR.mkdir(parents=True, exist_ok=True)
        out_path = OUT_DIR / f"{timestamp}_network.json"
        try:
            out_path.write_text(json.dumps(report, indent=2), encoding="utf-8")
        except Exception as e:
            log.warning("agent-network-monitor: could not save partial report — %s", e)
        return {
            "status":              status,
            "summary":             summary,
            "metrics":             {"external_calls_24h": 0, "known_domains": 0, "unknown_domains": 0},
            "action_items":        [],
            "escalate":            False,
            "escalation_reason":   "",
            "report_path":         str(out_path) if "out_path" in dir() else "",
            "model_available":     is_available(MODEL, host=OLLAMA_HOST),
        }

    # ── Extract domains ────────────────────────────────────────────────────────
    all_domains = _extract_domains_from_lines(lines, cutoff)
    known, unknown, api_key_domains = _categorize_domains(all_domains)
    call_count = len(all_domains)

    # ── LLM summary ───────────────────────────────────────────────────────────
    summary = _llm_summarize(all_domains, known, unknown, api_key_domains, call_count, files_read)

    # ── Build report ───────────────────────────────────────────────────────────
    escalate = len(unknown) > 0
    action_items: list[str] = []
    if unknown:
        action_items.append(
            f"Review unknown domain(s) in agent logs: {', '.join(unknown[:5])}"
        )
    if len(all_domains) > 20:
        action_items.append(
            f"Unusually high external call volume: {call_count} domains seen in 24h — investigate."
        )

    report = {
        "timestamp":          now.isoformat(),
        "date":               date.today().isoformat(),
        "status":             "alert" if escalate else "success",
        "summary":            summary,
        "external_calls_24h": call_count,
        "known_domains":      known,
        "unknown_domains":    unknown,
        "api_key_domains":    api_key_domains,
        "files_scanned":      files_read,
        "safe_domain_list":   sorted(SAFE_DOMAINS),
        "escalate":           escalate,
        "action_items":       action_items,
    }

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    out_path = OUT_DIR / f"{timestamp}_network.json"
    try:
        out_path.write_text(json.dumps(report, indent=2), encoding="utf-8")
        log.info("agent-network-monitor: saved to %s", out_path)
    except Exception as e:
        log.error("agent-network-monitor: failed to save report — %s", e)

    return {
        "status":      "alert" if escalate else "success",
        "summary":     summary,
        "metrics": {
            "external_calls_24h": call_count,
            "known_domains":      len(known),
            "unknown_domains":    len(unknown),
            "api_key_domains":    len(api_key_domains),
            "files_scanned":      files_read,
        },
        "action_items":      action_items,
        "escalate":          escalate,
        "escalation_reason": (
            f"{len(unknown)} unknown domain(s) detected: {', '.join(unknown[:3])}"
            if escalate else ""
        ),
        "known_domains":     known,
        "unknown_domains":   unknown,
        "api_key_domains":   api_key_domains,
        "report_path":       str(out_path),
        "model_available":   is_available(MODEL, host=OLLAMA_HOST),
    }
